import tests

test_dict = {
    "t-test of a regression coefficient": tests.eleven,
    "t-test of a correlation coefficient": tests.twelve,
    "Z-test of a correlation coefficient": tests.thirteen,
    "Z-test for two correlation coefficients": tests.fourteen,
    "F-test for two population variances (variance ratio test)": tests.sixteen,
    "F-test for two population variances (with correlated observations)": tests.seventeen,
    "F-test for K population means (analysis of variance)": tests.twenty_two,
    "χ2-test for an assumed population variance": tests.twenty_four,
    "F-test for the overall mean of K subpopulations (analysis of variance)": tests.twenty_six,
    "Bartlett’s test for equality of K variances": tests.thirty_one,
    "Hartley’s test for equality of K variances": tests.thirty_two,
    "The w/s-test for normality of a population": tests.thirty_three,
    "The Kolmogorov–Smirnov test for goodness of fit": tests.thirty_five,
    "The Kolmogorov–Smirnov test for comparing two populations": tests.thirty_six,
    "The χ2-test for goodness of fit": tests.thirty_seven,
    "The χ2-test for compatibility of K counts": tests.thirty_eight,
    "The χ2-test for consistency in a 2 × 2 table": tests.fourty,
    "The χ2-test for consistency in a K × 2 table": tests.fourty_one,
    "The Cochran test for consistency in an n × K table of dichotomous data": tests.fourty_two,
    "The χ2-test for consistency in a 2 × K table": tests.fourty_three,
    "The χ2-test for independence in a p × q table": tests.fourty_four,
    "The sign test for a median":tests.fourty_five,
    "The sign test for two medians (Paired Observation)": tests.fourty_six,
    "The signed rank test for a mean":tests.fourty_seven,
    "The signed rank test for two means (paired observations)": tests.fourty_eight,
    "The Wilcoxon inversion test (U-test)":tests.fourty_nine,
    "The median test of two populations":tests.fifty,
    "The median test of K populations":tests.fifty_one,
    "The Wilcoxon–Mann–Whitney rank sum test of two populations":tests.fifty_two,
    "The Siegel–Tukey rank sum dispersion test of two variances":tests.fifty_three,
}
